name: Docker Image CI/CD

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:latest
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: cd team-rocket && docker build -t pokemon-app .

      - name: Run tests
        run: docker run -e CI=true pokemon-app npm run test

      - name: Push Docker image to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker tag pokemon-app ${{ secrets.DOCKERHUB_USERNAME }}/pokemon-app:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/pokemon-app:${{ github.sha }}
